// GENERATED by scripts/generate-profile.mjs. Do not edit by hand.
// Source: profile.md (external); public-copy policy lives in the generator.
export const profileSourceHash = "b112f3d0ad82f2b5d7de6f3e5500078dede0ce8d60860b84046685279d3d4783";
export const graphNodes = [
  {
    "id": "me",
    "group": "root",
    "title": "Abdelrhman Ehab",
    "meta": "Frontend Engineer · Arabic: Native · English: Professional working proficiency",
    "summary": "Frontend Engineer with 4+ years of professional web-development experience, including 2+ years building production React, Angular, and Vue applications with TypeScript. Specializes in Arabic-first and bilingual RTL interfaces, complex forms, role-based access control, dashboards, and workflow-heavy products across healthcare, virtualization, regulatory, editorial, and e-commerce domains. Experienced in building Node.js/Express services and delivering applications through GitHub Actions, Docker, Nginx, Linux, and Cloudflare. Strong at turning complex requirements into maintainable, accessible, and production-ready user experiences.",
    "bullets": [
      "DevOps & Server Infrastructure: VM console with encrypted WebSocket connectivity and managed TLS.",
      "Data-Driven Features: file import validation audit, error-handling logic; MongoDB queries and debugging."
    ],
    "tags": [
      "React (Vite, TanStack Router, React Query, shadcn/ui)",
      "Angular (v17-18 migrations, Nx, Metronic)",
      "Vue (Pinia, vue-router)",
      "Node.js",
      "Express"
    ],
    "label": "Abdelrhman Ehab"
  },
  {
    "id": "hub-experience",
    "group": "hub",
    "sectionId": "experience",
    "title": "Experience",
    "meta": "8 engagements",
    "summary": "Career note: The Riyada, Virtuwa, and Pro Event roles were part-time engagements held concurrently with my full-time position at Smartly Techs. Dates below reflect the actual engagement periods.",
    "label": "Experience"
  },
  {
    "id": "hub-projects",
    "group": "hub",
    "sectionId": "projects",
    "title": "Projects",
    "meta": "16 products",
    "summary": "Product and open-source work across the profile.",
    "label": "Projects"
  },
  {
    "id": "hub-skills",
    "group": "hub",
    "sectionId": "skills",
    "title": "Core Skills",
    "meta": "",
    "summary": "Core Skills from the professional profile.",
    "label": "Core Skills"
  },
  {
    "id": "hub-domains",
    "group": "hub",
    "title": "Domains",
    "meta": "",
    "summary": "Domains from the professional profile.",
    "label": "Domains"
  },
  {
    "id": "hub-craft",
    "group": "hub",
    "title": "How I Work",
    "meta": "",
    "summary": "How I Work from the professional profile.",
    "label": "How I Work"
  },
  {
    "id": "hub-connect",
    "group": "hub",
    "sectionId": "contact",
    "title": "Connect",
    "meta": "",
    "summary": "Connect from the professional profile.",
    "label": "Connect"
  },
  {
    "id": "role-smartly-fse",
    "group": "role",
    "sectionId": "experience",
    "title": "Full Stack Engineer - Smartly Techs",
    "meta": "Jun 2025 - Present | Hybrid · Full-time",
    "summary": "Promoted to Full Stack Engineer after joining Smartly as a Frontend Web Developer in Feb 2024; delivered features across regulatory, competition, editorial, and collaboration products.",
    "bullets": [
      "Built a secure bidding-wallet flow with Node.js and Next.js, enforcing a minimum 10% balance requirement before bidding and placing funds on hold during active bids."
    ],
    "label": "Smartly Techs · Full Stack Engin"
  },
  {
    "id": "role-smartly-fe",
    "group": "role",
    "sectionId": "experience",
    "title": "Frontend Web Developer - Smartly Techs",
    "meta": "Feb 2024 - Nov 2025 | On-site · Full-time",
    "summary": "Developed the Faster Meeting platform in Next.js with authenticated scheduling, editing, and management of Zoom meetings through custom .NET APIs.",
    "bullets": [
      "Improved EFA UI/UX and web performance, increasing Lighthouse from 61 to 84 by optimizing LCP, FCP, and layout shifts.",
      "Enhanced UI/UX and performance in Boots & Ladders using Vue.js."
    ],
    "label": "Smartly Techs · Frontend"
  },
  {
    "id": "role-virtuwa-freelance",
    "group": "role",
    "sectionId": "experience",
    "title": "Freelance Frontend Engineer - Virtuwa",
    "meta": "2026 - Present | Remote · Contract follow-up",
    "summary": "Continue follow-up frontend development after the part-time engagement, maintaining and extending virtualization management products for client needs.",
    "bullets": [
      "Deliver product improvements across VM consoles, backup/recovery, host management, deployment workflows, bilingual UX, and operational interfaces.",
      "Continue hardening and productizing the frontend so the platform can be adapted and marketed for future clients."
    ],
    "label": "Virtuwa · Freelance Fronte"
  },
  {
    "id": "role-virtuwa-pt",
    "group": "role",
    "sectionId": "experience",
    "title": "Frontend Web Developer - Virtuwa",
    "meta": "Oct 2025 - May 2026 | Saudi Arabia (Remote) · Part-time",
    "summary": "Delivered VirtuWa HV - Hypervisor Management Interface (Oct 2025 - Jan 2026, 3 months), VirtuWa Cloud Manager - Enterprise Hypervisor Control Plane (in development), Virtuwa Flow Bridge (in development).",
    "bullets": [],
    "label": "Virtuwa · Frontend"
  },
  {
    "id": "role-riyada",
    "group": "role",
    "sectionId": "experience",
    "title": "Frontend Web Developer - Riyada Al Arabiya For Information Technology",
    "meta": "Jan 2026 - Mar 2026 | Saudi Arabia (Remote) · Part-time",
    "summary": "Contributed to the Laravel-to-Vue 3 migration of Care Connect Dashboard, delivering appointment table/calendar workflows with Pinia-managed filters.",
    "bullets": [
      "Implemented and validated recurring and overnight scheduling, date/time mapping, status-transition rules, disabled actions, and same-day check-in gating.",
      "Worked on Watu, a university platform, refactoring the Apply Now flow into a unified multi-step form and integrating location/information-request APIs.",
      "Performed end-to-end QA, identified functional and UX gaps, and prepared prioritized reports and team action plans for delivery."
    ],
    "label": "Riyada Al Arabiya  · Frontend"
  },
  {
    "id": "role-pro-event",
    "group": "role",
    "sectionId": "experience",
    "title": "Software Engineer - Pro Event",
    "meta": "Jul 2025 - Mar 2026 | Cairo (Remote) · Part-time",
    "summary": "Proposed creating a dedicated software section in the company and led the migration direction from Salla/Zid to WordPress + WooCommerce.",
    "bullets": [
      "Built and standardized the storefront UI across core pages (product, category, blog, and checkout) with a consistent design system and light/dark themes.",
      "Improved product discovery and engagement through navigation restructuring, service menu updates, category icon enhancements, and WhatsApp CTA integration.",
      "Expanded content and marketing capabilities by implementing the blog and SEO-focused sections across key pages.",
      "Delivered campaign and trust updates, including homepage/store promotional banners and customer-logo social proof integration."
    ],
    "label": "Pro Event · Software Enginee"
  },
  {
    "id": "role-independent-qr",
    "group": "role",
    "sectionId": "experience",
    "title": "Independent Product Development - QR Verification Platform",
    "meta": "2026 - Present | Productization · ",
    "summary": "Continued improving the QR-verification platform beyond the initial Sara Beauty delivery so it can be reused and marketed for future clients.",
    "bullets": [
      "Hardened the service with rate limiting, session revocation, audit events, CORS/security controls, and automated unit/Playwright coverage for concurrency, security, and performance paths.",
      "Added GitHub Actions CI, Node.js 22 LTS support, accessibility and contrast improvements, local font delivery, and clearer separation of export services."
    ],
    "label": "QR Verification Pl · Independent Prod"
  },
  {
    "id": "role-shortcutadv",
    "group": "role",
    "sectionId": "experience",
    "title": "WordPress Developer - Shortcutadv",
    "meta": "Jan 2022 - Jan 2024 | Saudi Arabia (Remote) · Full-time",
    "summary": "Customized WordPress themes and integrated plugins to meet diverse client requirements, ensuring responsive design, cross-browser compatibility, and optimized performance.",
    "bullets": [
      "Developed websites from scratch, implementing tailored features, SEO best practices, and user-friendly navigation to enhance brand presence and client engagement."
    ],
    "label": "Shortcutadv · WordPress Develo"
  },
  {
    "id": "proj-clinic-flow",
    "group": "project",
    "title": "Clinic Flow",
    "meta": "Product work",
    "summary": "Building an Arabic-first, RTL clinic operations app centered on same-day Visit Intake, doctor queue management, patient files, and staff access control.",
    "bullets": [
      "Implementing reception workflows for creating today’s queue entries, explicitly selecting returning Patient Files, and auto-creating new Patient Files for first-time patients.",
      "Adding doctor-facing queue and patient-detail screens with session history, session-charge context, and day-scoped queue behavior.",
      "Implementing protected routes and role-based access for reception, queue, patients, patient detail, and staff management.",
      "Shipped to a real clinic where a doctor adopted it for daily use; feedback was very positive, praising how easy it was to use and how directly it solved his day-to-day workflow problem.",
      "Tech stack: React 19, TypeScript, TanStack Router, TanStack Query, Better Auth, Drizzle, Tailwind CSS, shadcn/ui."
    ],
    "label": "Clinic Flow"
  },
  {
    "id": "proj-bleu-blog",
    "group": "project",
    "title": "BLEU Community Blog (Eleventy/Tailwind open-source tech community website)",
    "meta": "Product work",
    "summary": "Contributed Arabic-first internationalization work across the website, including locale data, localized routes/pages, RTL-aware UI behavior, and a language switcher.",
    "bullets": [
      "Added and refined Arabic/English translation files for home, blogs, blog details, shared UI copy, and contributing flows.",
      "Improved Arabic UX terminology and consistency for contributor-facing labels, merge-request wording, and category filtering.",
      "Strengthened localization reliability with i18n validation and localized-build verification scripts.",
      "Improved frontend quality by fixing semantic blog datetime output and moving font loading from CSS import into the document head for better performance.",
      "Followed a Git/GitHub open-source workflow on a feature branch and maintained repo hygiene around the project's npm-based dependency setup."
    ],
    "label": "BLEU Community Blog (Elevent"
  },
  {
    "id": "proj-gas-reg",
    "group": "project",
    "title": "GAS-REG Portal",
    "meta": "(in development)",
    "summary": "Built the Angular 21 frontend for complex regulatory and HSE workflows using standalone components, routing, and Reactive Forms.",
    "bullets": [
      "Created reusable ControlValueAccessor and signal-based controls, then assembled conditional permission-request sections with FormArray-driven dynamic fields.",
      "Delivered bilingual Arabic/English UX with Transloco and RTL/LTR switching, plus in-app XLSX editing through Syncfusion Spreadsheet.",
      "Integrated login/session handling and mapped complex frontend form state into backend submission payloads."
    ],
    "label": "GAS-REG Portal"
  },
  {
    "id": "proj-competition-admin",
    "group": "project",
    "title": "Competition Management Admin",
    "meta": "Product work",
    "summary": "Built a role-based React/TypeScript administration platform for system admins, supervisors, judges, and reviewers.",
    "bullets": [
      "Implemented the competition lifecycle from creation and judge assignment through participant/submission review and winner tracking.",
      "Added state-dependent route and action guards for judging, approvals, eligibility, next-review handling, and scoring workflows.",
      "Integrated TOTP/MFA, Arabic error handling, winner-rank validation up to 120, and required-score validation up to 300.",
      "Delivered bilingual RTL dashboards, reports, exports, and reusable data tables with TanStack Router/Query/Table, Zod, and Vitest."
    ],
    "label": "Competition Management Admin"
  },
  {
    "id": "proj-akhbar-admin",
    "group": "project",
    "title": "Akhbar AlKhaleej Admin FE",
    "meta": "Product work",
    "summary": "Led frontend delivery of a modular Angular SPA with standalone components and lazy-loaded routes for editorial administration.",
    "bullets": [
      "Designed JWT login/refresh, persistent session hydration, route guards, and RBAC scoping by role, section, and category.",
      "Built create/edit/publish workflows with status tracking, drafts, version history, and unsaved-changes protection.",
      "Delivered RTL rich-text editing, media-library insertion, image cropping, galleries, and reusable dashboard components.",
      "Standardized API integration, shared lookup caching/prefetching, and error/toast handling across the dashboard."
    ],
    "label": "Akhbar AlKhaleej Admin FE"
  },
  {
    "id": "proj-bidding-wallet",
    "group": "project",
    "title": "Bidding Wallet Flow",
    "meta": "Product work",
    "summary": "Built a secure bidding-wallet flow with Node.js and Next.js, enforcing a minimum 10% balance requirement before bidding and placing funds on hold during active bids.",
    "bullets": [],
    "label": "Bidding Wallet Flow"
  },
  {
    "id": "proj-faster-meeting",
    "group": "project",
    "title": "Faster Meeting",
    "meta": "Product work",
    "summary": "Developed the Faster Meeting platform in Next.js with authenticated scheduling, editing, and management of Zoom meetings through custom .NET APIs.",
    "bullets": [],
    "label": "Faster Meeting"
  },
  {
    "id": "proj-efa",
    "group": "project",
    "title": "EFA",
    "meta": "Product work",
    "summary": "Improved EFA UI/UX and web performance, increasing Lighthouse from 61 to 84 by optimizing LCP, FCP, and layout shifts.",
    "bullets": [],
    "label": "EFA"
  },
  {
    "id": "proj-boots-ladders",
    "group": "project",
    "title": "Boots & Ladders",
    "meta": "Product work",
    "summary": "Enhanced UI/UX and performance in Boots & Ladders using Vue.js.",
    "bullets": [],
    "label": "Boots & Ladders"
  },
  {
    "id": "proj-virtuwa-hv",
    "group": "project",
    "href": "https://virtuwa.com/",
    "linkLabel": "Visit VirtuWa",
    "title": "VirtuWa HV - Hypervisor Management Interface",
    "meta": "(Oct 2025 - Jan 2026, 3 months)",
    "summary": "Built a React/TypeScript hypervisor management console with live monitoring, RBAC, and bilingual English/Arabic UX.",
    "bullets": [
      "Delivered VM lifecycle workflows (power, clone, snapshots, console), storage/network management, and backup/restore interfaces with search and filtering.",
      "Hardened the console session handling with session-based bootstrap and short-lived, opaque identifiers.",
      "Shipped the product to a startup environment with early users and mentored a new frontend developer through implementation and delivery."
    ],
    "label": "VirtuWa HV"
  },
  {
    "id": "proj-virtuwa-cloud",
    "group": "project",
    "title": "VirtuWa Cloud Manager - Enterprise Hypervisor Control Plane",
    "meta": "(in development)",
    "summary": "Building a React/TypeScript control plane for VMs, hosts, clusters, storage, networking, licensing, and events.",
    "bullets": [
      "Implemented VM lifecycle actions and a browser-based noVNC/WebSocket console, with monitoring dashboards for CPU, memory, network, and IOPS.",
      "Added searchable, filterable, paginated event/audit logs with CSV/JSON export and auth UX for token refresh and inactivity logout.",
      "Documented backend contract improvements that reduced frontend normalization and clarified API integration requirements."
    ],
    "label": "VirtuWa Cloud Manager"
  },
  {
    "id": "proj-flow-bridge",
    "group": "project",
    "title": "Virtuwa Flow Bridge",
    "meta": "(in development)",
    "summary": "Implemented CI/CD with GitHub Actions for install, typecheck, tests, build verification, and private-runner deployment.",
    "bullets": [
      "Designed repeatable deployments with versioned releases, managed release switching, protected secrets, and setup documentation for future maintainers.",
      "Built target-host management, connection testing, process actions, user management, authentication, and activity/dashboard API integrations.",
      "Expanded bilingual localization and RTL support, and added a shared typed API client with a standardized Vite proxy configuration."
    ],
    "label": "Virtuwa Flow Bridge"
  },
  {
    "id": "proj-care-connect",
    "group": "project",
    "title": "Care Connect Dashboard",
    "meta": "Product work",
    "summary": "Contributed to the Laravel-to-Vue 3 migration of Care Connect Dashboard, delivering appointment table/calendar workflows with Pinia-managed filters.",
    "bullets": [],
    "label": "Care Connect Dashboard"
  },
  {
    "id": "proj-watu",
    "group": "project",
    "title": "Watu",
    "meta": "Product work",
    "summary": "Worked on Watu, a university platform, refactoring the Apply Now flow into a unified multi-step form and integrating location/information-request APIs.",
    "bullets": [],
    "label": "Watu"
  },
  {
    "id": "proj-pro-event-storefront",
    "group": "project",
    "title": "Pro Event Storefront",
    "meta": "Product work",
    "summary": "Built and standardized the storefront UI across core pages (product, category, blog, and checkout) with a consistent design system and light/dark themes.",
    "bullets": [],
    "label": "Pro Event Storefront"
  },
  {
    "id": "proj-qr-verify",
    "group": "project",
    "href": "https://verify.sarabeauty.net/scan",
    "linkLabel": "Open live scanner",
    "title": "QR-code verification platform (Sara Beauty)",
    "meta": "Product work",
    "summary": "Built a full-stack Node.js/Express and MongoDB QR-verification service used internally to generate and manage 1,000,000+ unique product codes.",
    "bullets": [
      "Designed idempotent batch generation, CSV exports, printable QR-label sheets, and an Arabic/RTL admin dashboard for manufacturing workflows.",
      "Delivered a consumer scanner with camera/manual entry and verification rules for first use, repeat scans, revocation, and expiry."
    ],
    "label": "QR-code verification platfor"
  },
  {
    "id": "skill-frameworks",
    "group": "skill",
    "title": "Programming & Frameworks",
    "meta": "Core skills",
    "tags": [
      "React (Vite, TanStack Router, React Query, shadcn/ui)",
      "Angular (v17-18 migrations, Nx, Metronic)",
      "Vue (Pinia, vue-router)",
      "Node.js",
      "Express",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Tailwind"
    ],
    "summary": "React (Vite, TanStack Router, React Query, shadcn/ui) · Angular (v17-18 migrations, Nx, Metronic) · Vue (Pinia, vue-router) · Node.js · Express · JavaScript · TypeScript · HTML5 · CSS3 · Bootstrap · Tailwind",
    "label": "Programming & Frameworks"
  },
  {
    "id": "skill-ecommerce",
    "group": "skill",
    "title": "E-commerce & CMS",
    "meta": "Core skills",
    "tags": [
      "OpenCart customizations",
      "Salla",
      "Zid & Shopify enhancements"
    ],
    "summary": "OpenCart customizations · Salla · Zid & Shopify enhancements",
    "label": "E-commerce & CMS"
  },
  {
    "id": "skill-devops",
    "group": "skill",
    "title": "DevOps & Infrastructure",
    "meta": "Core skills",
    "tags": [
      "AWS Lightsail",
      "Docker",
      "Docker Compose",
      "GitHub Actions CI/CD (self-hosted runners, private deployments)",
      "Automated frontend build & deploy pipelines (pnpm -> dist -> Nginx)",
      "Nginx reverse proxy",
      "SSL/TLS",
      "WebSocket proxying",
      "Linux administration",
      "least-privilege deployment permissions and Linux troubleshooting",
      "Cloudflare Pages / Workers"
    ],
    "summary": "AWS Lightsail · Docker · Docker Compose · GitHub Actions CI/CD (self-hosted runners, private deployments) · Automated frontend build & deploy pipelines (pnpm -> dist -> Nginx) · Nginx reverse proxy · SSL/TLS · WebSocket proxying · Linux administration · least-privilege deployment permissions and Linux troubleshooting · Cloudflare Pages / Workers",
    "label": "DevOps & Infrastructure"
  },
  {
    "id": "skill-data",
    "group": "skill",
    "title": "Databases & Analytics",
    "meta": "Core skills",
    "tags": [
      "SQL Server",
      "MongoDB / Atlas"
    ],
    "summary": "SQL Server · MongoDB / Atlas",
    "bullets": [
      "Data-Driven Features: file import validation audit, error-handling logic; MongoDB queries and debugging."
    ],
    "label": "Databases & Analytics"
  },
  {
    "id": "skill-other",
    "group": "skill",
    "title": "Other",
    "meta": "Core skills",
    "tags": [
      "Bilingual translation (Arabic <-> English)",
      "High-fidelity UI/UX integration with brand guidelines",
      "Performance optimization"
    ],
    "summary": "Bilingual translation (Arabic <-> English) · High-fidelity UI/UX integration with brand guidelines · Performance optimization",
    "label": "Other"
  },
  {
    "id": "skill-tools",
    "group": "skill",
    "title": "Tools",
    "meta": "Tools",
    "tags": [
      "Git",
      "GitHub",
      "Jira",
      "Postman",
      "Visual Studio",
      "VS Code",
      "Docker",
      "Nginx",
      "Mongo Shell",
      "MySQL Workbench",
      "PowerShell",
      "Linux Terminal",
      "Figma (UI integration)"
    ],
    "summary": "Git · GitHub · Jira · Postman · Visual Studio · VS Code · Docker · Nginx · Mongo Shell · MySQL Workbench · PowerShell · Linux Terminal · Figma (UI integration)",
    "label": "Tools"
  },
  {
    "id": "domain-healthcare",
    "group": "domain",
    "title": "Medical",
    "meta": "Industry / product domain",
    "summary": "Medical · listed industry",
    "label": "Medical"
  },
  {
    "id": "domain-virtualization",
    "group": "domain",
    "title": "Virtualization",
    "meta": "Industry / product domain",
    "summary": "Virtualization · represented in product work",
    "label": "Virtualization"
  },
  {
    "id": "domain-regulatory",
    "group": "domain",
    "title": "Regulatory",
    "meta": "Industry / product domain",
    "summary": "Regulatory · represented in product work",
    "label": "Regulatory"
  },
  {
    "id": "domain-editorial",
    "group": "domain",
    "title": "Journalism",
    "meta": "Industry / product domain",
    "summary": "Journalism · listed industry",
    "label": "Journalism"
  },
  {
    "id": "domain-ecommerce",
    "group": "domain",
    "title": "E-commerce",
    "meta": "Industry / product domain",
    "summary": "E-commerce · listed industry",
    "label": "E-commerce"
  },
  {
    "id": "domain-public",
    "group": "domain",
    "title": "Education",
    "meta": "Industry / product domain",
    "summary": "Education · represented in product work",
    "label": "Education"
  },
  {
    "id": "craft-cicd",
    "group": "craft",
    "title": "CI/CD & Deployment Automation",
    "meta": "Practice",
    "summary": "Designed and implemented a self-hosted GitHub Actions runner on a private Linux server to enable CI/CD without exposing SSH publicly.",
    "bullets": [
      "Automated frontend pipeline: pnpm install -> build -> dist -> Nginx deployment -> safe reload.",
      "Least-privilege sudo rules scoped to the deployment commands only.",
      "Ensured zero-downtime frontend updates with configuration validation before reload.",
      "Reduced manual deployment effort to a single Git push -> live deployment."
    ],
    "label": "CI/CD & Deployment Automatio"
  },
  {
    "id": "craft-bilingual",
    "group": "craft",
    "title": "Bilingual & RTL Engineering",
    "meta": "Practice",
    "summary": "Arabic: Native",
    "bullets": [
      "English: Professional working proficiency",
      "Bilingual translation (Arabic <-> English)",
      "Contributed Arabic-first internationalization work across the website, including locale data, localized routes/pages, RTL-aware UI behavior, and a language switcher.",
      "Added and refined Arabic/English translation files for home, blogs, blog details, shared UI copy, and contributing flows."
    ],
    "label": "Bilingual & RTL Engineering"
  },
  {
    "id": "craft-security",
    "group": "craft",
    "title": "Access Control & Security",
    "meta": "Practice",
    "summary": "Built a React/TypeScript hypervisor management console with live monitoring, RBAC, and bilingual English/Arabic UX.",
    "bullets": [
      "Hardened the console session handling with session-based bootstrap and short-lived, opaque identifiers."
    ],
    "label": "Access Control & Security"
  },
  {
    "id": "craft-performance",
    "group": "craft",
    "title": "Performance & Quality",
    "meta": "Practice",
    "summary": "Improved EFA UI/UX and web performance, increasing Lighthouse from 61 to 84 by optimizing LCP, FCP, and layout shifts.",
    "bullets": [
      "Improved frontend quality by fixing semantic blog datetime output and moving font loading from CSS import into the document head for better performance."
    ],
    "label": "Performance & Quality"
  },
  {
    "id": "craft-ways-of-working",
    "group": "craft",
    "title": "Ways of Working",
    "meta": "Practice",
    "summary": "Team leadership, requirements clarification, documentation, bilingual communication",
    "bullets": [],
    "label": "Ways of Working"
  },
  {
    "id": "link-email",
    "group": "link",
    "title": "Email",
    "summary": "abdelrhmanehab047@gmail.com",
    "href": "mailto:abdelrhmanehab047@gmail.com",
    "meta": "Connect",
    "linkLabel": "Email",
    "label": "Email"
  },
  {
    "id": "link-linkedin",
    "group": "link",
    "title": "LinkedIn",
    "summary": "https://www.linkedin.com/in/abdelrahman-ehab-87261a244/",
    "href": "https://www.linkedin.com/in/abdelrahman-ehab-87261a244/",
    "meta": "Connect",
    "linkLabel": "LinkedIn",
    "label": "LinkedIn"
  },
  {
    "id": "link-github",
    "group": "link",
    "title": "GitHub",
    "summary": "https://github.com/abdelrhmanehab10",
    "href": "https://github.com/abdelrhmanehab10",
    "meta": "Connect",
    "linkLabel": "GitHub",
    "label": "GitHub"
  },
  {
    "id": "link-resume",
    "group": "link",
    "title": "Resume (PDF)",
    "summary": "Download the full resume.",
    "href": "./assets/abdelrhmanehab_resume.pdf",
    "meta": "Connect",
    "linkLabel": "Resume (PDF)",
    "label": "Resume (PDF)"
  }
];
export const graphEdges = [
  {
    "source": "me",
    "target": "hub-experience",
    "type": "contains"
  },
  {
    "source": "me",
    "target": "hub-projects",
    "type": "contains"
  },
  {
    "source": "me",
    "target": "hub-skills",
    "type": "contains"
  },
  {
    "source": "me",
    "target": "hub-domains",
    "type": "contains"
  },
  {
    "source": "me",
    "target": "hub-craft",
    "type": "contains"
  },
  {
    "source": "me",
    "target": "hub-connect",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-smartly-fse",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-smartly-fe",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-virtuwa-freelance",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-virtuwa-pt",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-riyada",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-pro-event",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-independent-qr",
    "type": "contains"
  },
  {
    "source": "hub-experience",
    "target": "role-shortcutadv",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-clinic-flow",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-bleu-blog",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-gas-reg",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-competition-admin",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-akhbar-admin",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-bidding-wallet",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-faster-meeting",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-efa",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-boots-ladders",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-virtuwa-hv",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-virtuwa-cloud",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-flow-bridge",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-care-connect",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-watu",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-pro-event-storefront",
    "type": "contains"
  },
  {
    "source": "hub-projects",
    "target": "proj-qr-verify",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-frameworks",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-ecommerce",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-devops",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-data",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-other",
    "type": "contains"
  },
  {
    "source": "hub-skills",
    "target": "skill-tools",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-healthcare",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-virtualization",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-regulatory",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-editorial",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-ecommerce",
    "type": "contains"
  },
  {
    "source": "hub-domains",
    "target": "domain-public",
    "type": "contains"
  },
  {
    "source": "hub-craft",
    "target": "craft-cicd",
    "type": "contains"
  },
  {
    "source": "hub-craft",
    "target": "craft-bilingual",
    "type": "contains"
  },
  {
    "source": "hub-craft",
    "target": "craft-security",
    "type": "contains"
  },
  {
    "source": "hub-craft",
    "target": "craft-performance",
    "type": "contains"
  },
  {
    "source": "hub-craft",
    "target": "craft-ways-of-working",
    "type": "contains"
  },
  {
    "source": "hub-connect",
    "target": "link-email",
    "type": "contains"
  },
  {
    "source": "hub-connect",
    "target": "link-linkedin",
    "type": "contains"
  },
  {
    "source": "hub-connect",
    "target": "link-github",
    "type": "contains"
  },
  {
    "source": "hub-connect",
    "target": "link-resume",
    "type": "contains"
  },
  {
    "source": "proj-gas-reg",
    "target": "role-smartly-fse",
    "type": "delivered-in"
  },
  {
    "source": "proj-competition-admin",
    "target": "role-smartly-fse",
    "type": "delivered-in"
  },
  {
    "source": "proj-akhbar-admin",
    "target": "role-smartly-fse",
    "type": "delivered-in"
  },
  {
    "source": "proj-bidding-wallet",
    "target": "role-smartly-fse",
    "type": "delivered-in"
  },
  {
    "source": "proj-faster-meeting",
    "target": "role-smartly-fe",
    "type": "delivered-in"
  },
  {
    "source": "proj-efa",
    "target": "role-smartly-fe",
    "type": "delivered-in"
  },
  {
    "source": "proj-boots-ladders",
    "target": "role-smartly-fe",
    "type": "delivered-in"
  },
  {
    "source": "proj-virtuwa-hv",
    "target": "role-virtuwa-pt",
    "type": "delivered-in"
  },
  {
    "source": "proj-virtuwa-cloud",
    "target": "role-virtuwa-pt",
    "type": "delivered-in"
  },
  {
    "source": "proj-flow-bridge",
    "target": "role-virtuwa-pt",
    "type": "delivered-in"
  },
  {
    "source": "proj-care-connect",
    "target": "role-riyada",
    "type": "delivered-in"
  },
  {
    "source": "proj-watu",
    "target": "role-riyada",
    "type": "delivered-in"
  },
  {
    "source": "proj-pro-event-storefront",
    "target": "role-pro-event",
    "type": "delivered-in"
  },
  {
    "source": "proj-qr-verify",
    "target": "role-pro-event",
    "type": "delivered-in"
  },
  {
    "source": "proj-qr-verify",
    "target": "role-independent-qr",
    "type": "continued-as"
  },
  {
    "source": "proj-virtuwa-cloud",
    "target": "role-virtuwa-freelance",
    "type": "continued-as"
  },
  {
    "source": "proj-clinic-flow",
    "target": "domain-healthcare",
    "type": "in-domain"
  },
  {
    "source": "proj-care-connect",
    "target": "domain-healthcare",
    "type": "in-domain"
  },
  {
    "source": "proj-virtuwa-hv",
    "target": "domain-virtualization",
    "type": "in-domain"
  },
  {
    "source": "proj-virtuwa-cloud",
    "target": "domain-virtualization",
    "type": "in-domain"
  },
  {
    "source": "proj-flow-bridge",
    "target": "domain-virtualization",
    "type": "in-domain"
  },
  {
    "source": "proj-gas-reg",
    "target": "domain-regulatory",
    "type": "in-domain"
  },
  {
    "source": "proj-akhbar-admin",
    "target": "domain-editorial",
    "type": "in-domain"
  },
  {
    "source": "proj-bleu-blog",
    "target": "domain-editorial",
    "type": "in-domain"
  },
  {
    "source": "proj-pro-event-storefront",
    "target": "domain-ecommerce",
    "type": "in-domain"
  },
  {
    "source": "proj-qr-verify",
    "target": "domain-ecommerce",
    "type": "in-domain"
  },
  {
    "source": "proj-competition-admin",
    "target": "domain-public",
    "type": "in-domain"
  },
  {
    "source": "proj-watu",
    "target": "domain-public",
    "type": "in-domain"
  },
  {
    "source": "role-virtuwa-pt",
    "target": "role-smartly-fse",
    "type": "concurrent-with"
  },
  {
    "source": "role-riyada",
    "target": "role-smartly-fse",
    "type": "concurrent-with"
  },
  {
    "source": "role-pro-event",
    "target": "role-smartly-fse",
    "type": "concurrent-with"
  },
  {
    "source": "role-smartly-fe",
    "target": "role-smartly-fse",
    "type": "continued-as"
  },
  {
    "source": "role-virtuwa-pt",
    "target": "role-virtuwa-freelance",
    "type": "continued-as"
  },
  {
    "source": "role-pro-event",
    "target": "role-independent-qr",
    "type": "continued-as"
  },
  {
    "source": "proj-flow-bridge",
    "target": "craft-cicd",
    "type": "evidences"
  },
  {
    "source": "proj-qr-verify",
    "target": "craft-cicd",
    "type": "evidences"
  },
  {
    "source": "proj-virtuwa-hv",
    "target": "craft-security",
    "type": "evidences"
  },
  {
    "source": "proj-akhbar-admin",
    "target": "craft-security",
    "type": "evidences"
  },
  {
    "source": "proj-competition-admin",
    "target": "craft-security",
    "type": "evidences"
  },
  {
    "source": "proj-clinic-flow",
    "target": "craft-security",
    "type": "evidences"
  },
  {
    "source": "proj-virtuwa-cloud",
    "target": "craft-security",
    "type": "evidences"
  },
  {
    "source": "proj-gas-reg",
    "target": "craft-bilingual",
    "type": "evidences"
  },
  {
    "source": "proj-bleu-blog",
    "target": "craft-bilingual",
    "type": "evidences"
  },
  {
    "source": "proj-akhbar-admin",
    "target": "craft-bilingual",
    "type": "evidences"
  },
  {
    "source": "proj-clinic-flow",
    "target": "craft-bilingual",
    "type": "evidences"
  },
  {
    "source": "proj-qr-verify",
    "target": "craft-bilingual",
    "type": "evidences"
  },
  {
    "source": "proj-efa",
    "target": "craft-performance",
    "type": "evidences"
  },
  {
    "source": "proj-bleu-blog",
    "target": "craft-performance",
    "type": "evidences"
  },
  {
    "source": "proj-boots-ladders",
    "target": "craft-performance",
    "type": "evidences"
  },
  {
    "source": "proj-care-connect",
    "target": "craft-ways-of-working",
    "type": "evidences"
  },
  {
    "source": "proj-virtuwa-hv",
    "target": "craft-ways-of-working",
    "type": "evidences"
  },
  {
    "source": "skill-devops",
    "target": "craft-cicd",
    "type": "evidences"
  },
  {
    "source": "skill-other",
    "target": "craft-bilingual",
    "type": "evidences"
  }
];
export const graphGroups = {
  "root": {
    "color": "#f8fafc",
    "size": 13,
    "label": "Me"
  },
  "hub": {
    "color": "#67e8f9",
    "size": 9,
    "label": "Sections"
  },
  "role": {
    "color": "#cbd5e1",
    "size": 6.5,
    "label": "Experience"
  },
  "project": {
    "color": "#e2e8f0",
    "size": 6,
    "label": "Projects"
  },
  "skill": {
    "color": "#94a3b8",
    "size": 6,
    "label": "Skills"
  },
  "domain": {
    "color": "#cbd5e1",
    "size": 6,
    "label": "Domains"
  },
  "craft": {
    "color": "#e2e8f0",
    "size": 6,
    "label": "Practices"
  },
  "link": {
    "color": "#94a3b8",
    "size": 5,
    "label": "Connect"
  }
};
export const profileDetails = {
  "contact": {
    "Email": "abdelrhmanehab047@gmail.com",
    "Phone": "+20 1090883652",
    "LinkedIn": "https://www.linkedin.com/in/abdelrahman-ehab-87261a244/",
    "GitHub": "https://github.com/abdelrhmanehab10",
    "Portfolio": "https://abdelrhmanehab10.github.io/abdelrhman-ehab-portfolio/"
  },
  "summary": "Frontend Engineer with 4+ years of professional web-development experience, including 2+ years building production React, Angular, and Vue applications with TypeScript. Specializes in Arabic-first and bilingual RTL interfaces, complex forms, role-based access control, dashboards, and workflow-heavy products across healthcare, virtualization, regulatory, editorial, and e-commerce domains. Experienced in building Node.js/Express services and delivering applications through GitHub Actions, Docker, Nginx, Linux, and Cloudflare. Strong at turning complex requirements into maintainable, accessible, and production-ready user experiences.",
  "jobTitle": "Frontend Engineer",
  "experienceYears": "4+ years of professional web-development experience",
  "careerNote": "Career note: The Riyada, Virtuwa, and Pro Event roles were part-time engagements held concurrently with my full-time position at Smartly Techs. Dates below reflect the actual engagement periods.",
  "industries": [
    "E-commerce",
    "Journalism",
    "Medical"
  ],
  "languages": [
    "Arabic: Native",
    "English: Professional working proficiency"
  ],
  "softSkills": [
    "Team leadership, requirements clarification, documentation, bilingual communication"
  ],
  "highlights": [
    "DevOps & Server Infrastructure: VM console with encrypted WebSocket connectivity and managed TLS.",
    "Data-Driven Features: file import validation audit, error-handling logic; MongoDB queries and debugging."
  ]
};
